# PostgreSQL com shell e gerenciador de pacotes
#   - cgr.dev/chainguard/postgres:latest-dev
#   - 155.54 MB
# PostgreSQL
#   - cgr.dev/chainguard/postgres:latest
#   - 144.35 MB
# Comando para executar container PostgreSQL
#   - docker container run -it -d --env-file .env --network cpf-hub-network --mount type=volume,source=cpf-hub-volume,target=/var/lib/postgresql/data --name cpf-hub-postgresql cgr.dev/chainguard/postgres:latest-dev
# Link de apoio
#   - https://images.chainguard.dev/directory/image/postgres/overview
# Comando para criar imagem
#   - docker image build -f Dockerfile-PostgreSQL -t cpf-hub-postgresql .
# Comando para executar container PostgreSQL após criação de imagem
#   - docker container run -it -d --publish 5432:5432 --env-file .env --network cpf-hub-network --mount type=volume,source=cpf-hub-volume,target=/var/lib/postgresql/data --name cpf-hub-postgresql cpf-hub-postgresql

FROM cgr.dev/chainguard/postgres:latest

COPY init.sql /var/lib/postgres/initdb/
