services:
  cpf-hub-flask:
    build:
      context: .
      dockerfile: Dockerfile-Flask
    container_name: cpf-hub-flask
    image: cpf-hub-flask:latest
    env_file: .env
    ports:
      - "5000:5000"
    networks:
      - cpf-hub-network
    depends_on:
      cpf-hub-postgresql:
        condition: service_healthy
  cpf-hub-postgresql:
    build:
      context: .
      dockerfile: Dockerfile-PostgreSQL
    container_name: cpf-hub-postgresql
    image: cpf-hub-postgresql:latest
    env_file: .env    
    ports:
      - "5432:5432"
    networks:
      - cpf-hub-network
    volumes:
      - type: volume
        source: cpf-hub-volume
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "cpf-hub-db"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  cpf-hub-network:
    driver: bridge

volumes: 
  cpf-hub-volume: